# Generated by Django 5.2.6 on 2025-09-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_at',
            new_name='create_dat',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
    ]
