# Generated by Django 5.2.6 on 2025-10-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_created_at_note_create_dat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='create_dat',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='note_images/'),
        ),
    ]
